-- =============================================================================
-- Base de conhecimento do atendimento (etapa 3, PR 3a) — seed dos 58 artigos do levantamento — 2026-10-03
-- GERADO por docs/sql/gerar_kb_seed.py a partir de Claude/Entregas/2026-09-30 Base de conhecimento —
-- levantamento inicial (blocos A01…A58). Não editar à mão: corrija o levantamento e gere de novo com
--   python3 docs/sql/gerar_kb_seed.py <levantamento.md> docs/sql/20261003_kb_seed.sql
-- Aplicar à mão no SQL Editor, DEPOIS de docs/sql/20261003_chat_bot.sql. NÃO vai para supabase/migrations.
-- 39 publicados (verdadeiro_hoje) e 19 rascunhos (depende_de_algo, com o motivo em review_note).
-- Os textos marcados nao_publicar ficam fora.
-- Idempotente: artigo que já existe (mesmo slug) não é tocado, então a edição feita no admin fica; artigo
-- excluído no admin (kb_slugs_excluidos) não volta.
-- =============================================================================
begin;

insert into public.kb_articles (slug, title, body, keywords, audience, department_id, status, origin, review_note)
select v.slug, v.title, v.body, v.keywords, v.audience, d.id, v.status, 'seed', v.review_note
from (values
  ('lev-a01', 'Como crio minha conta na Evokaa?',
   'Clique em "Criar Conta" no topo do site. No primeiro passo, escolha Produtor (organiza eventos) ou Participante (vai a eventos). A tela já abre marcada em Produtor: se você só vai comprar ingressos, clique em Participante. Preencha nome, sobrenome, e-mail e a senha (duas vezes) e clique em "Avançar". No segundo passo, aceite os Termos de Uso e a Política de Privacidade e clique em "Criar Conta". A senha precisa ter pelo menos 8 caracteres, com letra maiúscula, letra minúscula, número e um símbolo do teclado (ex.: !@#$). Acento e espaço não contam como símbolo.',
   'cadastro, cadastrar, criar conta, registrar, abrir conta, inscrever, sign up, nova conta, senha não aceita, senha fraca', 'all', 'suporte_tecnico', 'published',
   null),
  ('lev-a02', 'Posso entrar com minha conta do Google?',
   'Pode. Na tela de entrar, marque a caixa de aceite dos Termos de Uso e da Política de Privacidade e clique em "Entrar com Google". No primeiro acesso, a conta é criada como participante, com o seu nome e a sua foto do Google. Entrar com Apple ou Microsoft ainda não está disponível. Para ser produtor, crie a conta pelo formulário "Criar Conta" e escolha "Produtor".',
   'google, gmail, login social, entrar com google, apple, microsoft, outlook, hotmail, login rápido', 'all', 'suporte_tecnico', 'published',
   null),
  ('lev-a03', 'Esqueci minha senha. Como recupero?',
   'Na tela de entrar, clique em "Esqueci a senha", digite o e-mail da sua conta e envie. Você recebe um link para criar uma senha nova. Se o e-mail não aparecer, olhe também a caixa de spam.',
   'esqueci senha, recuperar senha, redefinir senha, resetar, não consigo entrar, perdi a senha, link de senha', 'all', 'suporte_tecnico', 'published',
   null),
  ('lev-a04', 'Como troco minha senha estando logado?',
   'Vá em Perfil, na parte "Segurança", e clique em "Alterar" ao lado de Senha. Você vai para a tela de recuperação: informe o seu e-mail e crie a senha nova pelo link que chegar.',
   'trocar senha, mudar senha, alterar senha, nova senha, segurança da conta', 'participant', 'suporte_tecnico', 'published',
   null),
  ('lev-a05', 'Posso trocar o e-mail da minha conta?',
   'Ainda não. O e-mail aparece bloqueado no Perfil, e a troca de e-mail não existe na plataforma por enquanto. Se você precisa mudar o e-mail, fale com a nossa equipe pelo formulário de contato.',
   'trocar email, mudar e-mail, alterar e-mail, e-mail errado, novo e-mail, email antigo', 'all', 'suporte_tecnico', 'published',
   null),
  ('lev-a06', 'Como altero meu telefone, cidade ou foto de perfil?',
   'Abra o Perfil, clique em editar e altere telefone (com o código do país), cidade, bio e data de nascimento. A cidade pode ser preenchida pelo CEP. Depois clique em salvar. Para trocar a foto, clique nela e escolha uma imagem.',
   'trocar telefone, mudar celular, número errado, editar perfil, foto de perfil, avatar, cidade, cep, dados pessoais', 'participant', 'suporte_tecnico', 'published',
   null),
  ('lev-a07', 'Como ativo a verificação em duas etapas (2FA)?',
   'Participante: vá em Perfil, na parte "Segurança", e ligue o interruptor "Autenticação de dois fatores". Produtor: vá em Configurações, aba "Conta & Segurança", e ligue "Autenticação 2FA". Você vai precisar de um aplicativo autenticador no celular, como o Google Authenticator ou o Microsoft Authenticator. Leia o QR Code que aparece (ou digite a chave mostrada embaixo dele) e confirme com o código de 6 dígitos do aplicativo. Depois de ativada, a verificação pede esse código a cada login. Para desativar, você precisa ter entrado com o código.',
   '2fa, dois fatores, duas etapas, autenticador, google authenticator, código de 6 dígitos, segurança extra', 'all', 'suporte_tecnico', 'draft',
   'O 2FA do banco (PR #69) está aplicado e o participante tem o interruptor no Perfil, mas falta um teste de ponta a ponta com conta real de participante e de produtor antes de publicar.'),
  ('lev-a08', 'Como excluo minha conta?',
   'Participante: em Configurações, na "Zona de Perigo", clique em "Excluir conta". Produtor: em Configurações, aba "Conta & Segurança", na "Zona de Perigo", clique em "Excluir". Digite EXCLUIR e clique em "Confirmar exclusão". A exclusão é imediata e não tem volta: seus dados pessoais são apagados ou tornados anônimos e o acesso é encerrado. Os registros de compras já feitas ficam guardados pelo prazo da lei fiscal, só com nome e CPF (e-mail e telefone saem). Produtor com evento publicado ainda por acontecer, ou com saque em andamento, precisa encerrar ou cancelar o evento e concluir o saque antes.',
   'excluir conta, apagar conta, deletar conta, encerrar conta, remover meus dados, sair da evokaa', 'all', 'privacidade', 'published',
   null),
  ('lev-a09', 'O que acontece com meus ingressos se eu excluir a conta?',
   'Os ingressos já emitidos para eventos futuros continuam válidos e no nome de quem comprou, mas deixam de aparecer para você, porque a conta deixa de existir. Antes de excluir, salve ou compartilhe o QR Code de cada ingresso: depois não dá para recuperar.',
   'excluir conta ingresso, perder ingresso, ingresso depois de apagar conta, qr code conta excluída', 'participant', 'privacidade', 'published',
   null),
  ('lev-a10', 'Onde vejo meus ingressos?',
   'Entre na sua conta e abra "Meus Ingressos" no menu. Dá para filtrar por Todos, Ativos e Histórico. O ingresso só aparece ali depois que o pagamento é confirmado. Um pedido ainda não pago aparece em "Compras", como Pendente.',
   'meus ingressos, onde está meu ingresso, não acho meu ingresso, ver ingresso, ingresso sumiu, bilhete, entrada', 'participant', 'atendimento_participante', 'draft',
   'A tela é real, mas o ingresso só nasce pelo webhook do gateway de pagamento, que ainda não existe (Decisões 57 e 60). Hoje ninguém tem ingresso emitido.'),
  ('lev-a11', 'Como mostro o QR Code do meu ingresso na entrada?',
   'Em "Meus Ingressos", toque em "Ver QR" no ingresso. O QR Code abre grande, com o código do ingresso escrito embaixo, caso a portaria precise digitar. Só ingresso ativo, com pagamento confirmado, mostra o QR.',
   'qr code, qrcode, código do ingresso, mostrar ingresso, entrada do evento, portaria, ler ingresso', 'participant', 'atendimento_participante', 'draft',
   'ingresso emitido (gateway) e a validação na portaria (função check-in-validate não publicada; ver A36)'),
  ('lev-a12', 'Vou receber o ingresso por e-mail ou em PDF?',
   'Ainda não. Por enquanto o ingresso fica só na sua conta, em "Meus Ingressos", e o e-mail de confirmação da compra ainda não é enviado. Se precisar mostrar o ingresso sem internet, faça uma captura de tela do QR Code.',
   'ingresso por email, pdf, baixar ingresso, imprimir ingresso, e-mail de confirmação, não recebi email, comprovante', 'participant', 'atendimento_participante', 'published',
   null),
  ('lev-a13', 'Posso transferir meu ingresso ou trocar o nome do titular?',
   'Ainda não. A Evokaa ainda não tem transferência de ingresso nem troca de titular. Se precisar, fale com a nossa equipe pelo chat ou pelo formulário de contato.',
   'transferir ingresso, passar ingresso, trocar nome, mudar titular, dar ingresso, revender, vender meu ingresso', 'participant', 'atendimento_participante', 'published',
   null),
  ('lev-a14', 'Tem meia-entrada?',
   'A plataforma ainda não tem configuração própria de meia-entrada: essa parte dos ingressos está em construção. Os tipos de ingresso de cada evento, com os preços, aparecem na página do evento. Para saber das regras de meia-entrada de um evento, fale com a nossa equipe.',
   'meia entrada, meia-entrada, estudante, idoso, desconto estudante, carteirinha, pcd, professor', 'participant', 'atendimento_participante', 'draft',
   'A obrigação legal de meia-entrada é assunto jurídico (lacuna L05); não publicar antes de o Ricardo confirmar o texto.'),
  ('lev-a15', 'Como cancelo meu ingresso ou peço reembolso?',
   'O cancelamento não é feito pelo app: fale com a nossa equipe pelo formulário de contato ou pelo chat. Pelos Termos de Uso, a política de reembolso de cada evento é responsabilidade do produtor. A Evokaa intermedeia a compra.',
   'cancelar ingresso, reembolso, devolução, estorno, desistir, arrependimento, quero meu dinheiro de volta, evento cancelado', 'participant', 'atendimento_participante', 'draft',
   'Não há reembolso real sem gateway (o admin diz que "reembolso fica desligado até a Fase 4", Pendências concluídas/A2b). Prazo e regra de arrependimento: lacuna L04 (jurídico).'),
  ('lev-a16', 'Como compro um ingresso?',
   'Abra a página do evento e clique em "Comprar Ingressos". Escolha a quantidade de cada tipo. Para continuar, é preciso entrar na conta, e o carrinho fica guardado enquanto você entra. Na tela de pagamento, escolha cartão de crédito ou Pix. O pedido é registrado como "Pendente" e só vira ingresso quando o pagamento é confirmado.',
   'comprar ingresso, como comprar, carrinho, finalizar compra, checkout, adquirir ingresso, pagar ingresso', 'all', 'atendimento_participante', 'draft',
   '(gateway de pagamento, Decisão 65, ainda em aberto)'),
  ('lev-a17', 'O pagamento online já está funcionando?',
   'Ainda não. O pagamento online da Evokaa ainda não está ligado. Por isso, nenhuma cobrança é feita e nenhum ingresso é emitido. Se você tentou pagar e apareceu uma mensagem de erro, ou se tem um pedido "Pendente" em Compras, fique tranquilo: nenhum valor foi cobrado por ele.',
   'pagamento não funciona, erro no pagamento, não consigo pagar, cartão recusado, pix não gera, cobrança, fui cobrado', 'all', 'financeiro', 'published',
   null),
  ('lev-a18', 'Quais formas de pagamento vocês aceitam?',
   'A tela de pagamento tem cartão de crédito e Pix. As duas formas dependem da integração de pagamento, que ainda não está ligada (veja "O pagamento online já está funcionando?"). Boleto, débito, dinheiro e transferência não estão disponíveis.',
   'formas de pagamento, pix, cartão de crédito, boleto, débito, parcelar, meios de pagamento, pagar com pix', 'all', 'financeiro', 'draft',
   '(gateway). Contradiz a FAQ da Home (ver seção 2)'),
  ('lev-a19', 'Meu pedido está como "Pendente". O que isso quer dizer?',
   '"Pendente" quer dizer que o pedido foi registrado, mas o pagamento ainda não foi confirmado. Nesse estado, o ingresso não é emitido. Em "Compras" você também pode ver Pago, Falhou, Cancelado e Reembolsado. Hoje, como o pagamento online ainda não está ligado, todo pedido fica Pendente e nenhum valor é cobrado.',
   'pedido pendente, aguardando pagamento, status do pedido, compras, pedido não confirmado, meu pedido', 'participant', 'financeiro', 'published',
   null),
  ('lev-a20', 'Posso parcelar a compra?',
   'Ainda não. O parcelamento está em construção e não aparece na compra.',
   'parcelar, parcelamento, vezes no cartão, sem juros, dividir pagamento', 'all', 'financeiro', 'published',
   null),
  ('lev-a21', 'Posso usar um cupom de desconto na compra do ingresso?',
   'Ainda não. A compra ainda não tem campo de cupom. Quando os cupons de evento forem liberados, o próprio produtor do evento vai criá-los e divulgá-los.',
   'cupom, código de desconto, promoção, desconto no ingresso, voucher, cupom não funciona', 'participant', 'atendimento_participante', 'published',
   null),
  ('lev-a22', 'Como encontro eventos na Evokaa?',
   'Clique em "Eventos" no topo do site (no celular, abra o menu primeiro). Dá para buscar pelo nome do evento, pela descrição ou pelo nome do local, escolher uma categoria (Festa, Corporativo, Workshop, Show, Palestra, Networking, Gastronomia, Esporte) e filtrar por data: hoje, este fim de semana, este mês, um dia específico ou um período. Se não achar o evento numa categoria, volte para "Todos": nem todo evento aparece nos filtros de categoria. Só aparecem eventos que ainda vão acontecer e que já foram aprovados pela equipe da Evokaa.',
   'buscar evento, procurar evento, eventos perto, agenda, programação, festas, shows, o que tem hoje, filtro', 'all', 'geral', 'published',
   null),
  ('lev-a23', 'O que encontro na página de um evento?',
   'A página mostra data, horário, local, descrição e os tipos de ingresso com preço. Nela ficam o botão "Comprar Ingressos" e o botão de compartilhar, que envia ou copia o link do evento.',
   'página do evento, detalhes do evento, local do evento, horário, preço do ingresso, compartilhar evento', 'all', 'geral', 'published',
   null),
  ('lev-a24', 'Abri o link e apareceu "Evento não encontrado". O que houve?',
   'Há três motivos possíveis: o evento ainda não foi aprovado pela equipe da Evokaa, foi retirado do ar ou o link está incompleto. Confira o link com quem enviou ou procure o evento em "Eventos". Se não achar, fale com a gente.',
   'evento não encontrado, link quebrado, evento sumiu, página não abre, evento não aparece', 'all', 'atendimento_participante', 'published',
   null),
  ('lev-a25', 'A Evokaa tem aplicativo para celular?',
   'Ainda não. O aplicativo vai estar disponível em breve na App Store e no Google Play. Por enquanto, use a Evokaa pelo navegador do celular, em evokaa.com.br.',
   'aplicativo, app, baixar app, play store, app store, android, iphone', 'all', 'geral', 'published',
   null),
  ('lev-a26', 'Como falo com o produtor do evento?',
   'O chat direto com o produtor ainda não está disponível na Evokaa. Se tiver dúvidas sobre o evento (horário, local, atrações), fale com a nossa equipe pelo chat ou pelo formulário de contato.',
   'falar com produtor, contato do organizador, organizador, dúvida sobre o evento, chat com produtor', 'participant', 'atendimento_participante', 'draft',
   'Falta confirmar que a equipe consegue encaminhar a dúvida ao produtor (lacuna L07).'),
  ('lev-a27', 'Como me cadastro como produtor de eventos?',
   'Clique em "Criar Conta" e escolha "Produtor". Se alguém indicou a Evokaa para você, digite o código dessa pessoa no campo "Código de indicação" (opcional). A conta de produtor é criada só por esse formulário: entrar com Google cria conta de participante.',
   'ser produtor, conta de produtor, organizar evento, vender ingressos, cadastro produtor, criar conta produtor', 'producer', 'comercial', 'published',
   null),
  ('lev-a28', 'Como crio um evento?',
   'No painel, clique em "Criar Evento". São cinco passos: escolha o tipo de evento; preencha nome, data, horário, local e capacidade; cadastre os lotes de ingresso com preço e quantidade; anote os custos, se quiser; e confira o resumo. No fim, clique em "Criar Evento". Mesmo que a mensagem diga "publicado", o evento ainda passa pela aprovação da equipe da Evokaa e só aparece ao público depois disso. Por enquanto não dá para escolher a imagem de capa na criação: o evento aparece com a imagem padrão.',
   'criar evento, novo evento, cadastrar evento, publicar evento, montar evento, anunciar evento', 'producer', 'suporte_produtor', 'draft',
   'A tela de criação vai ser refeita (Decisão 87); hoje a capa é fixa, a mensagem final diz "publicado" e o evento nasce pendente. Reescrever quando a tela nova sair.'),
  ('lev-a29', 'Por que meu evento ainda não aparece no site?',
   'Todo evento novo passa pela aprovação da equipe da Evokaa antes de ir ao ar. Enquanto não é aprovado, ele não aparece em "Eventos" nem abre pelo link público, mesmo que em Meus Eventos ele apareça como "Ativo" e a mensagem ao criar diga "publicado". Se você editar um evento, ele volta para a aprovação. A equipe pode aprovar, recusar ou, depois, suspender a aprovação. Se o evento for recusado, o motivo aparece quando você abre a edição dele em Meus Eventos.',
   'evento não aparece, aprovação, moderação, evento pendente, aguardando aprovação, evento reprovado, rejeitado', 'producer', 'suporte_produtor', 'published',
   null),
  ('lev-a30', 'Quais são os planos e preços para produtores?',
   'São cinco planos, com preço mensal: Evo Free (R$ 0), Evo Starter (R$ 37), Evo Plus (R$ 97), Evo Pro (R$ 167) e Evo Enterprise (R$ 312). A cobrança das assinaturas ainda não está ligada. Enquanto isso, as ferramentas do painel do produtor ficam liberadas para todos, sem depender do plano. A exceção são os créditos do Evo: sem assinatura ativa, a conta usa a cota do plano Free.',
   'planos, preços, quanto custa, mensalidade, assinatura, free, starter, plus, pro, enterprise, grátis', 'producer', 'comercial', 'published',
   null),
  ('lev-a31', 'Qual é a taxa sobre a venda de ingressos?',
   'Cada plano tem uma taxa de venda, descontada de cada ingresso vendido: Free 12% (mínimo R$ 3,99), Starter 8% (mínimo R$ 2,99), Plus 6% (mínimo R$ 1,99), Pro 4% (sem mínimo) e Enterprise 2,5%, negociável. Pagando por trimestre, semestre ou ano, a mensalidade tem 5%, 10% ou 20% de desconto.',
   'taxa, comissão da evokaa, percentual, quanto a evokaa cobra, taxa por ingresso, desconto anual, trimestral', 'producer', 'financeiro', 'draft',
   'A Decisão 88 (30/09) troca a taxa: 10% com mínimo de R$ 3, paga pelo comprador. O código ainda mostra a taxa por plano (PricingSection) e 5% no checkout. Reescrever do zero quando a nova taxa estiver no checkout e na página de planos.'),
  ('lev-a32', 'Como assino um plano ou mudo de plano?',
   'Ainda não dá para contratar nem trocar de plano pela plataforma: a área de Assinatura está em construção e a cobrança ainda não está ligada. Por isso, hoje nenhum plano é cobrado e não há assinatura para cancelar. Enquanto isso, todo produtor usa as ferramentas do painel sem restrição de plano.',
   'assinar plano, mudar plano, upgrade, trocar de plano, contratar, cancelar assinatura, downgrade', 'producer', 'comercial', 'published',
   null),
  ('lev-a33', 'Posso criar cupons de desconto para o meu evento?',
   'Ainda não. A tela "Cupons" aparece no menu do painel, mas ainda não salva os cupons direito e vai ser refeita. A compra do ingresso também ainda não tem campo de cupom. Quando os cupons forem liberados, o cupom do evento vai ser criado e bancado pelo próprio produtor: o desconto sai do seu repasse.',
   'criar cupom, cupom de desconto, promoção, código promocional, desconto no evento, cupom não salva', 'producer', 'suporte_produtor', 'published',
   null),
  ('lev-a34', 'O que é o Evo?',
   'O Evo é o assistente de inteligência artificial da Evokaa para produtores. Ele ajuda a planejar e criar eventos: calcula referências de normas de segurança, estima consumo e lotes e monta uma proposta de rascunho. O Evo só sugere: nada é criado, publicado ou pago sem o seu clique. Para abrir, clique no Evo no canto inferior direito do painel.',
   'evo, assistente, inteligência artificial, ia, chatgpt, robô, ajuda para planejar, gemini', 'producer', 'suporte_produtor', 'published',
   null),
  ('lev-a35', 'Quantos créditos do Evo eu tenho e como eles funcionam?',
   'Cada plano tem créditos do Evo por mês: Free 5, Starter 5, Plus 20, Pro 60 e Enterprise 1.000 (com uso justo). Como a cobrança dos planos ainda não está ligada, quem não tem assinatura ativa usa a cota do Free. Pergunta simples gasta 1 crédito; pedido mais complexo (planejar evento, fazer cálculos) gasta 3. O seu saldo aparece no próprio Evo. Os créditos voltam cheios no dia 1º de cada mês (horário de Brasília), e o que sobrou não passa para o mês seguinte. Se o Evo der erro e não responder, você não perde crédito. Também existe um limite de perguntas por hora. Ainda não dá para comprar créditos.',
   'créditos, créditos do evo, acabou crédito, limite do evo, quantas perguntas, renovar créditos, comprar créditos', 'producer', 'suporte_produtor', 'draft',
   'Conferir os valores de ai_settings (cotas e custos) no banco de produção antes de publicar; não existe envio de imagem ao Evo, por isso o texto não fala de imagem.'),
  ('lev-a36', 'Como faço o check-in dos participantes no dia do evento?',
   'O check-in pela Evokaa ainda não está pronto para uso no evento. A tela "Check-in" existe no painel, mas a validação dos ingressos ainda está sendo ligada, e a leitura do QR pela câmera ainda não existe. Se o seu evento está próximo, fale com a nossa equipe para combinar a portaria.',
   'check-in, checkin, portaria, validar ingresso, ler qr code, lista de convidados, entrada, scanner', 'producer', 'suporte_produtor', 'draft',
   'Os PRs #72 e #69 estão mesclados; falta publicar a função check-in-validate e ligar o gateway (sem ele não há ingresso emitido).'),
  ('lev-a37', 'Quais ferramentas do painel do produtor já funcionam?',
   'O menu do painel mostra as ferramentas disponíveis. As que ainda estão em construção ficam fora do menu; se você abrir uma delas por um link antigo, aparece o aviso "Em construção". Algumas telas do menu ainda não estão prontas de verdade: Cupons, Tarefas e Caixinha ainda não salvam tudo direito, e o Check-in ainda não valida ingressos. Se uma tela der erro ou não salvar, fale com a gente pelo Evo, na aba "Falar com a Evokaa".',
   'o que funciona, ferramentas, recursos, painel do produtor, funcionalidades, em breve, em construção', 'producer', 'suporte_produtor', 'draft',
   'Conferir tela a tela (Cupons, Tarefas, Caixinha e Check-in) e as colunas no banco antes de publicar.'),
  ('lev-a38', 'Como me torno afiliado da Evokaa?',
   'O Afiliado Evokaa indica a plataforma para produtores de eventos e ganha comissão sobre os planos que eles contratam. Para participar, escreva para contato@evokaa.com.br ou use o formulário de contato com o assunto "Quero ser afiliado". A equipe analisa e, se aprovar, abre a sua Área do Afiliado.',
   'ser afiliado, programa de afiliados, indicar, revender, parceiro, ganhar comissão, trabalhar com a evokaa', 'all', 'parcerias', 'published',
   null),
  ('lev-a39', 'Quanto ganha o Afiliado Evokaa e como recebe?',
   'Na primeira venda, o afiliado recebe 50% do valor efetivamente pago pelo plano, já com o desconto do cupom, se houver. Nas mensalidades seguintes, a comissão recorrente fica entre 15% e 25%, conforme o acordo de cada afiliado. A comissão vai direto para a conta de recebimento do afiliado, pela divisão automática do pagamento. A cobrança dos planos ainda não está ligada, então nenhuma comissão foi gerada até agora. Indicar a si mesmo não é permitido.',
   'comissão afiliado, quanto ganho, recorrência, pagamento de comissão, split, quando recebo, 50%', 'all', 'parcerias', 'draft',
   'gateway com divisão direta para a conta do afiliado (Decisão 65, em aberto), contrato do afiliado (jurídico) e "valor pago ou líquido" (em aberto)'),
  ('lev-a40', 'Como funciona o meu link de afiliado?',
   'Na Área do Afiliado, crie um link com nome para cada canal (Instagram, WhatsApp, e-mail). O link fica no formato evokaa.com.br/p/SEUCODIGO/nome. Quem abre cai direto nos planos, e o produtor que se cadastra depois fica ligado a você. Se a pessoa aceitar os cookies de análise, o código fica guardado no navegador dela por 30 dias. Se não aceitar, vale só naquela visita: se ela fechar ou recarregar a página, o código se perde. Por isso, passe também o seu código: o produtor pode digitá-lo no campo "Código de indicação" do cadastro. Se a pessoa abrir links de dois afiliados, vale o último.',
   'link de afiliado, meu link, rastreamento, cookie, indicação, código de indicação, cliques', 'all', 'parcerias', 'draft',
   'Falta o teste de ponta a ponta do link de afiliado (cadastro de produtor pelo link).'),
  ('lev-a41', 'Posso oferecer cupom de desconto aos produtores que indico?',
   'Pode, mas é a Evokaa que cria o cupom. Na Área do Afiliado, peça um cupom escolhendo a faixa de desconto (5, 10, 15, 20 ou 25%) e a validade (até 30 dias). A equipe analisa e, se aprovar, o cupom aparece em "Meus cupons". Cada produtor pode usar o cupom uma vez.',
   'cupom de afiliado, desconto para indicado, pedir cupom, cupom de plano, código promocional', 'all', 'parcerias', 'draft',
   'o cupom só tem efeito quando a cobrança de planos existir (gateway).'),
  ('lev-a42', 'Qual a diferença entre o Afiliado Evokaa e o afiliado de um evento?',
   'O Afiliado Evokaa indica a plataforma para produtores e vai ganhar comissão sobre os planos que os indicados contratarem. A cobrança dos planos ainda não começou, então por enquanto nenhuma comissão foi gerada. O afiliado de evento é outra coisa: ele divulga os ingressos de um evento específico, e as regras são combinadas direto com o produtor desse evento. Esse programa ainda está em fase de testes.',
   'tipos de afiliado, afiliado de evento, vender ingresso como afiliado, promoter, divulgador', 'all', 'parcerias', 'published',
   null),
  ('lev-a43', 'Sou afiliado de um evento. Como minhas vendas são contadas?',
   'O programa de afiliados de evento está em fase de testes (beta). A venda feita pelo seu link ainda não é ligada automaticamente ao seu código, então a conferência das vendas e o pagamento da comissão são combinados direto com o produtor do evento.',
   'afiliado de evento, comissão de evento, vendas pelo link, promoter, quanto vendi, receber comissão', 'all', 'parcerias', 'published',
   null),
  ('lev-a44', 'Quais dados pessoais a Evokaa coleta?',
   'Coletamos os dados de cadastro (nome, e-mail, telefone), de perfil (foto, preferências), das compras, de navegação (cookies e registros) e, para produtores, o uso do Evo. Se você usa o chat de atendimento, guardamos também as mensagens, os arquivos que você anexar e o nome e o telefone que você informa nele. Por obrigação legal, guardamos ainda data, hora e IP de cada login e o registro do seu aceite dos Termos e da Política. Os detalhes estão na Política de Privacidade.',
   'dados coletados, quais dados, informações pessoais, o que vocês guardam, lgpd, privacidade', 'all', 'privacidade', 'published',
   null),
  ('lev-a45', 'Quais são os meus direitos sobre os meus dados e como peço?',
   'Você pode pedir acesso aos seus dados, correção, anonimização, bloqueio ou eliminação, revogar o consentimento e pedir a portabilidade. Para isso, use o formulário em /contato ou escreva para o Encarregado de Dados, no e-mail dpo@evokaa.com.br. Para apagar a conta inteira, você mesmo pode excluí-la em Configurações.',
   'lgpd, meus direitos, apagar dados, acessar dados, portabilidade, dpo, encarregado, titular, corrigir dados', 'all', 'privacidade', 'published',
   null),
  ('lev-a46', 'A Evokaa vende ou compartilha meus dados?',
   'Não vendemos seus dados. Compartilhamos só o necessário: com o produtor do evento para o qual você comprou ingresso, com a empresa que processa o pagamento da compra, com os fornecedores que hospedam a plataforma e enviam nossos e-mails, com as ferramentas de medição de audiência (Vercel e Google), com o Google para as conversas com o Evo e quando a lei ou a Justiça exigir.',
   'vendem meus dados, compartilhamento, terceiros, quem vê meus dados, produtor vê meus dados', 'all', 'privacidade', 'published',
   null),
  ('lev-a47', 'Como funcionam os cookies e como mudo minha escolha?',
   'Os cookies essenciais (login e funcionamento) não dependem do seu consentimento. O Google Analytics e o nosso registro de uso só ligam se você aceitar os cookies de análise. O Vercel Web Analytics não usa cookies. Para mudar a escolha a qualquer momento, use o link "Cookies" no rodapé das páginas públicas do site, como a página inicial. Dentro do painel da sua conta esse rodapé não aparece. Se você retirar o consentimento, o Google Analytics é desligado e os cookies dele são apagados.',
   'cookies, aceitar cookies, recusar cookies, google analytics, rastreamento, mudar consentimento', 'all', 'privacidade', 'published',
   null),
  ('lev-a48', 'Por quanto tempo meus dados ficam guardados?',
   'Os registros de login (data, hora e IP) ficam 6 meses e depois são apagados automaticamente. O registro do seu aceite dos Termos fica enquanto a conta existir e, depois, pelo prazo de defesa de direitos. Os registros de compras ficam pelo prazo da legislação fiscal. O registro de uso do Evo fica até você pedir para apagar.',
   'tempo de guarda, retenção, quanto tempo guardam, apagar histórico, registros de acesso', 'all', 'privacidade', 'published',
   null),
  ('lev-a49', 'O que o Evo faz com as minhas mensagens?',
   'O que você escreve ao Evo é processado pelo Google (API paga do Gemini) em nome da Evokaa. O Google não usa esse conteúdo para treinar os produtos dele e o guarda por 55 dias, só para impedir abusos. A conversa não fica gravada nos servidores da Evokaa. Guardamos só um registro de cada uso, com um resumo curto da mensagem em que e-mails, telefones e CPF ficam ocultos. Não escreva dados pessoais de outras pessoas no chat do Evo.',
   'evo privacidade, ia e meus dados, gemini, google, treinamento, conversa gravada', 'producer', 'privacidade', 'published',
   null),
  ('lev-a50', 'Como paro de receber a newsletter?',
   'Clique em "Descadastrar-se" no próprio e-mail da newsletter e confirme na página que abrir. O descadastro só vale depois do clique de confirmação.',
   'newsletter, descadastrar, parar de receber e-mails, sair da lista, spam, cancelar inscrição', 'all', 'privacidade', 'published',
   null),
  ('lev-a51', 'Como falo com a Evokaa?',
   'Você pode usar o formulário em /contato (nome, e-mail, telefone e mensagem são obrigatórios), escrever para contato@evokaa.com.br ou chamar no WhatsApp (41) 99758-5425. Pelo formulário, respondemos no seu e-mail. Nosso endereço é Rua Treze de Maio, 336, salas 33 e 34, Curitiba/PR.',
   'contato, falar com a evokaa, telefone, whatsapp, e-mail, endereço, suporte, atendimento, sac', 'all', 'geral', 'draft',
   'O telefone do texto ainda não é a linha definitiva da empresa (Decisão 38). O Contact.tsx:70-73 lista suporte@, vendas@, parcerias@ e feedback@, e não confirmei que essas caixas existem. O "Resposta instantânea" do WhatsApp (:175) é promessa: não repeti. Ao publicar, incluir o chat ("pelo chat, depois de entrar na sua conta").'),
  ('lev-a52', 'Qual é o horário de atendimento?',
   '(texto a definir) Nosso atendimento humano funciona de segunda a sexta, das 9h às 18h (horário de Brasília). Mensagens enviadas fora desse horário são respondidas no próximo dia útil.',
   'horário, horário de atendimento, que horas, fim de semana, sábado, domingo, feriado, plantão', 'all', 'geral', 'draft',
   'Três textos diferentes (sábado sim ou não; 1 dia útil ou 24 horas úteis) e o horário ainda é decisão do Ricardo (especificação do chat, linha 222). Ver a lacuna L01.'),
  ('lev-a53', 'Como funciona o chat de atendimento?',
   'Para conversar pelo chat, você precisa entrar na sua conta. Sem conta, use o formulário em /contato. O chat abre pelo balão no canto inferior direito do site e, dentro da sua conta, pelo Evo. Toque em "Enviar mensagem", escolha o assunto e preencha nome, telefone (WhatsApp) e a mensagem. O e-mail usado é o da sua conta. Na maioria dos assuntos, nosso assistente responde primeiro, com base nos artigos da nossa central de ajuda, e pergunta "Isso resolveu?". Se você tocar em "Não", se ele não encontrar a resposta ou se você tocar em "Falar com um atendente", a conversa passa para uma pessoa da equipe, e ele avisa quando isso acontecer. Quando a equipe responder e você ainda não tiver visto, mandamos um aviso para o e-mail da sua conta. A resposta fica no chat.',
   'chat, conversar, atendimento online, robô, bot, assistente, como funciona o chat', 'all', 'geral', 'published',
   null),
  ('lev-a54', 'Quero falar com uma pessoa, não com o robô.',
   'Enquanto o assistente está atendendo, o botão "Falar com um atendente" fica no alto da conversa. É só tocar nele. Você também pode responder "Não" em "Isso resolveu?", e a conversa passa para uma pessoa da equipe. Se o assistente não souber a resposta, ele mesmo passa. E, se você escolher o assunto "Dia do evento: check-in e portaria", "Pagamento: cobrança, Pix ou cartão" ou "Meus dados e privacidade (LGPD)", a conversa já vai direto para a equipe, sem assistente.',
   'falar com humano, atendente, pessoa real, não quero robô, suporte humano, transferir atendimento', 'all', 'geral', 'draft',
   'Publicado, o assistente responde este artigo a quem escreve "quero falar com uma pessoa", em vez de passar para a equipe (Decisão 83; teste T12 #25 em 30/09). Hoje só o botão conta como pedido; publicar só se o texto "falar com uma pessoa/atendente" passar a ser reconhecido como pedido.'),
  ('lev-a55', 'Como mando uma sugestão ou aviso de um erro no site?',
   'Dentro da sua conta, toque no ícone de Feedback no alto da tela, escolha o tipo (Melhoria, Bug, Dúvida, Sugestão ou Elogio), escreva o que você viu ou sugere e envie. O feedback serve para melhorar a plataforma e não abre um atendimento. Se o problema estiver impedindo você de usar a conta, fale com o atendimento pelo chat ou pelo formulário em /contato.',
   'sugestão, feedback, reportar erro, bug, problema no site, melhoria, reclamação', 'all', 'suporte_tecnico', 'published',
   null),
  ('lev-a56', 'O que é a Evokaa?',
   'A Evokaa é uma plataforma de ingressos e gestão de eventos: produtores criam, divulgam e vendem ingressos, e o público descobre e compra. A empresa por trás é a Evoka Soluções Ltda, CNPJ 68.076.437/0001-42, de Curitiba/PR.',
   'o que é, sobre a evokaa, quem são vocês, empresa, cnpj, é confiável', 'site', 'geral', 'published',
   null),
  ('lev-a57', 'A Evokaa é a organizadora dos eventos?',
   'Não. Quem organiza é o produtor de cada evento, responsável pelas informações do evento, pelo cumprimento da lei, pela política de reembolso e pela experiência do público. A Evokaa oferece a plataforma e intermedeia a venda.',
   'quem organiza, responsável pelo evento, evento ruim, reclamação do evento, organizador', 'all', 'geral', 'published',
   null),
  ('lev-a58', 'Que tipo de evento posso criar na Evokaa?',
   'Ao clicar em "Criar Evento" no painel, você escolhe o tipo: Balada, Casamento, Festival, Corporativo, Show, Aniversário ou Formatura. Na busca do site, só os tipos Corporativo e Show têm filtro próprio; eventos dos outros tipos aparecem em "Todos". Todo evento passa pela moderação da equipe antes de aparecer para o público.',
   'tipos de evento, categorias, posso vender, que eventos aceitam, festa, workshop, show', 'producer', 'comercial', 'published',
   null)
) as v(slug, title, body, keywords, audience, setor, status, review_note)
join public.chat_departments d on d.slug = v.setor
where not exists (select 1 from public.kb_slugs_excluidos x where x.slug = v.slug)
on conflict (slug) do nothing;

-- Conferência: os 58 estão na base ou foram excluídos pelo admin (setor que não casou também cai aqui)
do $$
declare
  v_n int := (select count(*) from public.kb_articles a where a.slug ~ '^lev-a[0-9]{2}$')
           + (select count(*) from public.kb_slugs_excluidos x where x.slug ~ '^lev-a[0-9]{2}$'
                and not exists (select 1 from public.kb_articles a where a.slug = x.slug));
begin
  if v_n <> 58 then
    raise exception 'seed da base: esperava 58 artigos (presentes + excluídos), achei %', v_n;
  end if;
end;
$$;

commit;
